/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.ViewQL;

import View.ViewLogin;
import java.awt.Color;

/**
 *
 * @author Admin
 */
public class ViewQuanLy extends javax.swing.JFrame {

    /**
     * Creates new form ViewQuanLySanPham
     */
    private Color defaulColor,
            /**
             * Creates new form ViewQuanLySanPham
             */
            clickedColor;

    public ViewQuanLy() {
        initComponents();
        defaulColor = new Color(145, 94, 65);
        clickedColor = new Color(156, 132, 122);
        QuanLySanPham.setBackground(defaulColor);
        ThongKe.setBackground(defaulColor);
        QuanLyNhanVien.setBackground(defaulColor);
        DangXuat.setBackground(defaulColor);
        QuanLyKhuyenMai.setBackground(defaulColor);

        QuanLySanPham.setBackground(clickedColor);
        ThongKe.setBackground(defaulColor);
        QuanLyNhanVien.setBackground(defaulColor);
        DangXuat.setBackground(defaulColor);
        QuanLyKhuyenMai.setBackground(defaulColor);

        ViewQuanLySanPham m = new ViewQuanLySanPham();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(m).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        QuanLyKhuyenMai = new javax.swing.JPanel();
        txtQuanLyKhuyenMai = new javax.swing.JLabel();
        QuanLySanPham = new javax.swing.JPanel();
        txtThanhToan = new javax.swing.JLabel();
        QuanLyBan = new javax.swing.JPanel();
        txtQuanLyBan = new javax.swing.JLabel();
        LichSuOrder = new javax.swing.JPanel();
        txtLichSuOrder1 = new javax.swing.JLabel();
        ThanhToan = new javax.swing.JPanel();
        txtThanhToan1 = new javax.swing.JLabel();
        ThongKe = new javax.swing.JPanel();
        txtLichSuOrder = new javax.swing.JLabel();
        DangXuat = new javax.swing.JPanel();
        txtDangXuat = new javax.swing.JLabel();
        QuanLyNhanVien = new javax.swing.JPanel();
        txtQuanLyNhanVien = new javax.swing.JLabel();
        anh = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(145, 94, 65));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel2MouseMoved(evt);
            }
        });

        QuanLyKhuyenMai.setBackground(new java.awt.Color(156, 132, 122));

        txtQuanLyKhuyenMai.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtQuanLyKhuyenMai.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtQuanLyKhuyenMai.setText("        Khuyến mãi");
        txtQuanLyKhuyenMai.setToolTipText("");
        txtQuanLyKhuyenMai.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtQuanLyKhuyenMaiMouseMoved(evt);
            }
        });
        txtQuanLyKhuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtQuanLyKhuyenMaiMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtQuanLyKhuyenMaiMousePressed(evt);
            }
        });

        javax.swing.GroupLayout QuanLyKhuyenMaiLayout = new javax.swing.GroupLayout(QuanLyKhuyenMai);
        QuanLyKhuyenMai.setLayout(QuanLyKhuyenMaiLayout);
        QuanLyKhuyenMaiLayout.setHorizontalGroup(
            QuanLyKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(QuanLyKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuanLyKhuyenMaiLayout.createSequentialGroup()
                    .addGap(0, 37, Short.MAX_VALUE)
                    .addComponent(txtQuanLyKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        QuanLyKhuyenMaiLayout.setVerticalGroup(
            QuanLyKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
            .addGroup(QuanLyKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(txtQuanLyKhuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
        );

        QuanLySanPham.setBackground(new java.awt.Color(156, 132, 122));

        txtThanhToan.setBackground(new java.awt.Color(156, 132, 122));
        txtThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtThanhToan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtThanhToan.setText("       Sản phẩm");
        txtThanhToan.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtThanhToanMouseMoved(evt);
            }
        });
        txtThanhToan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtThanhToanMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtThanhToanMousePressed(evt);
            }
        });

        QuanLyBan.setBackground(new java.awt.Color(156, 132, 122));

        txtQuanLyBan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtQuanLyBan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtQuanLyBan.setText("      Bàn");
        txtQuanLyBan.setToolTipText("");
        txtQuanLyBan.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtQuanLyBanMouseMoved(evt);
            }
        });
        txtQuanLyBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtQuanLyBanMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtQuanLyBanMousePressed(evt);
            }
        });

        javax.swing.GroupLayout QuanLyBanLayout = new javax.swing.GroupLayout(QuanLyBan);
        QuanLyBan.setLayout(QuanLyBanLayout);
        QuanLyBanLayout.setHorizontalGroup(
            QuanLyBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuanLyBanLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtQuanLyBan, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        QuanLyBanLayout.setVerticalGroup(
            QuanLyBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtQuanLyBan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        );

        LichSuOrder.setBackground(new java.awt.Color(156, 132, 122));

        txtLichSuOrder1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtLichSuOrder1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtLichSuOrder1.setText("      Lịch sử order");
        txtLichSuOrder1.setToolTipText("");
        txtLichSuOrder1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtLichSuOrder1MouseMoved(evt);
            }
        });
        txtLichSuOrder1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLichSuOrder1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtLichSuOrder1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout LichSuOrderLayout = new javax.swing.GroupLayout(LichSuOrder);
        LichSuOrder.setLayout(LichSuOrderLayout);
        LichSuOrderLayout.setHorizontalGroup(
            LichSuOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LichSuOrderLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtLichSuOrder1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        LichSuOrderLayout.setVerticalGroup(
            LichSuOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LichSuOrderLayout.createSequentialGroup()
                .addComponent(txtLichSuOrder1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        ThanhToan.setBackground(new java.awt.Color(156, 132, 122));

        txtThanhToan1.setBackground(new java.awt.Color(156, 132, 122));
        txtThanhToan1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtThanhToan1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtThanhToan1.setText("     Bán hàng");
        txtThanhToan1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtThanhToan1MouseMoved(evt);
            }
        });
        txtThanhToan1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtThanhToan1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtThanhToan1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout ThanhToanLayout = new javax.swing.GroupLayout(ThanhToan);
        ThanhToan.setLayout(ThanhToanLayout);
        ThanhToanLayout.setHorizontalGroup(
            ThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThanhToanLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtThanhToan1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ThanhToanLayout.setVerticalGroup(
            ThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThanhToanLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtThanhToan1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout QuanLySanPhamLayout = new javax.swing.GroupLayout(QuanLySanPham);
        QuanLySanPham.setLayout(QuanLySanPhamLayout);
        QuanLySanPhamLayout.setHorizontalGroup(
            QuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuanLySanPhamLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(ThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LichSuOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(QuanLyBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        QuanLySanPhamLayout.setVerticalGroup(
            QuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuanLySanPhamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(LichSuOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(QuanLyBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        ThongKe.setBackground(new java.awt.Color(156, 132, 122));

        txtLichSuOrder.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtLichSuOrder.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtLichSuOrder.setText("       Thống kê");
        txtLichSuOrder.setToolTipText("");
        txtLichSuOrder.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtLichSuOrderMouseMoved(evt);
            }
        });
        txtLichSuOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLichSuOrderMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtLichSuOrderMousePressed(evt);
            }
        });

        javax.swing.GroupLayout ThongKeLayout = new javax.swing.GroupLayout(ThongKe);
        ThongKe.setLayout(ThongKeLayout);
        ThongKeLayout.setHorizontalGroup(
            ThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThongKeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtLichSuOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ThongKeLayout.setVerticalGroup(
            ThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongKeLayout.createSequentialGroup()
                .addComponent(txtLichSuOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        DangXuat.setBackground(new java.awt.Color(156, 132, 122));

        txtDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtDangXuat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtDangXuat.setText("         Đăng xuất");
        txtDangXuat.setToolTipText("");
        txtDangXuat.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtDangXuatMouseMoved(evt);
            }
        });
        txtDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDangXuatMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDangXuatMousePressed(evt);
            }
        });

        javax.swing.GroupLayout DangXuatLayout = new javax.swing.GroupLayout(DangXuat);
        DangXuat.setLayout(DangXuatLayout);
        DangXuatLayout.setHorizontalGroup(
            DangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DangXuatLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        DangXuatLayout.setVerticalGroup(
            DangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        QuanLyNhanVien.setBackground(new java.awt.Color(156, 132, 122));

        txtQuanLyNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtQuanLyNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtQuanLyNhanVien.setText("         Nhân viên");
        txtQuanLyNhanVien.setToolTipText("");
        txtQuanLyNhanVien.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtQuanLyNhanVienMouseMoved(evt);
            }
        });
        txtQuanLyNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtQuanLyNhanVienMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtQuanLyNhanVienMousePressed(evt);
            }
        });

        javax.swing.GroupLayout QuanLyNhanVienLayout = new javax.swing.GroupLayout(QuanLyNhanVien);
        QuanLyNhanVien.setLayout(QuanLyNhanVienLayout);
        QuanLyNhanVienLayout.setHorizontalGroup(
            QuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(QuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuanLyNhanVienLayout.createSequentialGroup()
                    .addGap(0, 33, Short.MAX_VALUE)
                    .addComponent(txtQuanLyNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        QuanLyNhanVienLayout.setVerticalGroup(
            QuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 79, Short.MAX_VALUE)
            .addGroup(QuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(QuanLyNhanVienLayout.createSequentialGroup()
                    .addComponent(txtQuanLyNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        anh.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        anh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        anh.setText("CoffeeShop");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(QuanLySanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(QuanLyKhuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(QuanLyNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(anh, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(anh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(QuanLySanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(QuanLyKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(QuanLyNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(DangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1079, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jDesktopPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtThanhToanMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtThanhToanMouseMoved
        QuanLySanPham.setBackground(clickedColor);
        ThongKe.setBackground(defaulColor);
        QuanLyNhanVien.setBackground(defaulColor);
        DangXuat.setBackground(defaulColor);
        QuanLyKhuyenMai.setBackground(defaulColor);
    }//GEN-LAST:event_txtThanhToanMouseMoved

    private void txtThanhToanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtThanhToanMouseClicked
        ViewQuanLySanPham m = new ViewQuanLySanPham();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(m).setVisible(true);
    }//GEN-LAST:event_txtThanhToanMouseClicked

    private void txtThanhToanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtThanhToanMousePressed
        QuanLySanPham.setBackground(clickedColor);
        ThongKe.setBackground(defaulColor);
        QuanLyNhanVien.setBackground(defaulColor);
        DangXuat.setBackground(defaulColor);
        QuanLyKhuyenMai.setBackground(defaulColor);
    }//GEN-LAST:event_txtThanhToanMousePressed

    private void txtLichSuOrderMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLichSuOrderMouseMoved
        QuanLySanPham.setBackground(defaulColor);
        ThongKe.setBackground(clickedColor);
        QuanLyNhanVien.setBackground(defaulColor);
        DangXuat.setBackground(defaulColor);
        QuanLyKhuyenMai.setBackground(defaulColor);
    }//GEN-LAST:event_txtLichSuOrderMouseMoved

    private void txtLichSuOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLichSuOrderMouseClicked
        ViewThongKe m = new ViewThongKe();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(m).setVisible(true);
    }//GEN-LAST:event_txtLichSuOrderMouseClicked

    private void txtLichSuOrderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLichSuOrderMousePressed
        QuanLySanPham.setBackground(defaulColor);
        ThongKe.setBackground(clickedColor);
        QuanLyNhanVien.setBackground(defaulColor);
        DangXuat.setBackground(defaulColor);
        QuanLyKhuyenMai.setBackground(defaulColor);
    }//GEN-LAST:event_txtLichSuOrderMousePressed

    private void txtDangXuatMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDangXuatMouseMoved
        QuanLySanPham.setBackground(defaulColor);
        ThongKe.setBackground(defaulColor);
        QuanLyNhanVien.setBackground(defaulColor);
        DangXuat.setBackground(clickedColor);
        QuanLyKhuyenMai.setBackground(defaulColor);
    }//GEN-LAST:event_txtDangXuatMouseMoved

    private void txtDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDangXuatMouseClicked
        this.dispose();
        ViewLogin m = new ViewLogin();
        m.setVisible(true);
    }//GEN-LAST:event_txtDangXuatMouseClicked

    private void txtDangXuatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDangXuatMousePressed
        QuanLySanPham.setBackground(defaulColor);
        ThongKe.setBackground(defaulColor);
        QuanLyNhanVien.setBackground(defaulColor);
        DangXuat.setBackground(clickedColor);
        QuanLyKhuyenMai.setBackground(defaulColor);
    }//GEN-LAST:event_txtDangXuatMousePressed

    private void txtQuanLyNhanVienMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtQuanLyNhanVienMouseMoved
        QuanLySanPham.setBackground(defaulColor);
        ThongKe.setBackground(defaulColor);
        QuanLyNhanVien.setBackground(clickedColor);
        DangXuat.setBackground(defaulColor);
        QuanLyKhuyenMai.setBackground(defaulColor);
    }//GEN-LAST:event_txtQuanLyNhanVienMouseMoved

    private void txtQuanLyNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtQuanLyNhanVienMouseClicked
        View.ViewQL.ViewQuanLyNhanVien m = new View.ViewQL.ViewQuanLyNhanVien();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(m).setVisible(true);
    }//GEN-LAST:event_txtQuanLyNhanVienMouseClicked

    private void txtQuanLyNhanVienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtQuanLyNhanVienMousePressed
        QuanLySanPham.setBackground(defaulColor);
        ThongKe.setBackground(defaulColor);
        QuanLyKhuyenMai.setBackground(defaulColor);
        QuanLyNhanVien.setBackground(clickedColor);
        DangXuat.setBackground(defaulColor);
    }//GEN-LAST:event_txtQuanLyNhanVienMousePressed

    private void jPanel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseMoved
        QuanLySanPham.setBackground(defaulColor);
        ThongKe.setBackground(defaulColor);
        QuanLyNhanVien.setBackground(defaulColor);
        QuanLyKhuyenMai.setBackground(defaulColor);
        DangXuat.setBackground(defaulColor);
    }//GEN-LAST:event_jPanel2MouseMoved

    private void txtQuanLyKhuyenMaiMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtQuanLyKhuyenMaiMouseMoved
        QuanLySanPham.setBackground(defaulColor);
        ThongKe.setBackground(defaulColor);
        QuanLyKhuyenMai.setBackground(clickedColor);
        QuanLyNhanVien.setBackground(defaulColor);
        DangXuat.setBackground(defaulColor);
    }//GEN-LAST:event_txtQuanLyKhuyenMaiMouseMoved

    private void txtQuanLyKhuyenMaiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtQuanLyKhuyenMaiMousePressed
        QuanLySanPham.setBackground(defaulColor);
        ThongKe.setBackground(defaulColor);
        QuanLyKhuyenMai.setBackground(clickedColor);
        QuanLyNhanVien.setBackground(defaulColor);
        DangXuat.setBackground(defaulColor);
    }//GEN-LAST:event_txtQuanLyKhuyenMaiMousePressed

    private void txtQuanLyKhuyenMaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtQuanLyKhuyenMaiMouseClicked
        ViewKhuyenMai m = new ViewKhuyenMai();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(m).setVisible(true);
    }//GEN-LAST:event_txtQuanLyKhuyenMaiMouseClicked

    private void txtThanhToan1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtThanhToan1MouseMoved
        ThanhToan.setBackground(clickedColor);
        LichSuOrder.setBackground(defaulColor);
        QuanLyBan.setBackground(defaulColor);
        DangXuat.setBackground(defaulColor);
    }//GEN-LAST:event_txtThanhToan1MouseMoved

    private void txtThanhToan1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtThanhToan1MouseClicked
        ViewThanhToan m = new ViewThanhToan();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(m).setVisible(true);
    }//GEN-LAST:event_txtThanhToan1MouseClicked

    private void txtThanhToan1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtThanhToan1MousePressed
        ThanhToan.setBackground(clickedColor);
        LichSuOrder.setBackground(defaulColor);
        QuanLyBan.setBackground(defaulColor);
        DangXuat.setBackground(defaulColor);
    }//GEN-LAST:event_txtThanhToan1MousePressed

    private void txtLichSuOrder1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLichSuOrder1MouseMoved
        ThanhToan.setBackground(defaulColor);
        LichSuOrder.setBackground(clickedColor);
        QuanLyBan.setBackground(defaulColor);
        DangXuat.setBackground(defaulColor);
    }//GEN-LAST:event_txtLichSuOrder1MouseMoved

    private void txtLichSuOrder1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLichSuOrder1MouseClicked
        ViewLichSu m = new ViewLichSu();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(m).setVisible(true);
    }//GEN-LAST:event_txtLichSuOrder1MouseClicked

    private void txtLichSuOrder1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLichSuOrder1MousePressed
        ThanhToan.setBackground(defaulColor);
        LichSuOrder.setBackground(clickedColor);
        QuanLyBan.setBackground(defaulColor);
        DangXuat.setBackground(defaulColor);
    }//GEN-LAST:event_txtLichSuOrder1MousePressed

    private void txtQuanLyBanMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtQuanLyBanMouseMoved
        ThanhToan.setBackground(defaulColor);
        LichSuOrder.setBackground(defaulColor);
        QuanLyBan.setBackground(clickedColor);
        DangXuat.setBackground(defaulColor);
    }//GEN-LAST:event_txtQuanLyBanMouseMoved

    private void txtQuanLyBanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtQuanLyBanMouseClicked
        ViewQuanLyBan m = new ViewQuanLyBan();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(m).setVisible(true);
    }//GEN-LAST:event_txtQuanLyBanMouseClicked

    private void txtQuanLyBanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtQuanLyBanMousePressed
        ThanhToan.setBackground(defaulColor);
        LichSuOrder.setBackground(defaulColor);
        QuanLyBan.setBackground(clickedColor);
        DangXuat.setBackground(defaulColor);
    }//GEN-LAST:event_txtQuanLyBanMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewQuanLySanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewQuanLySanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewQuanLySanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewQuanLySanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewQuanLy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DangXuat;
    private javax.swing.JPanel LichSuOrder;
    private javax.swing.JPanel QuanLyBan;
    private javax.swing.JPanel QuanLyKhuyenMai;
    private javax.swing.JPanel QuanLyNhanVien;
    private javax.swing.JPanel QuanLySanPham;
    private javax.swing.JPanel ThanhToan;
    private javax.swing.JPanel ThongKe;
    private javax.swing.JLabel anh;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txtDangXuat;
    private javax.swing.JLabel txtLichSuOrder;
    private javax.swing.JLabel txtLichSuOrder1;
    private javax.swing.JLabel txtQuanLyBan;
    private javax.swing.JLabel txtQuanLyKhuyenMai;
    private javax.swing.JLabel txtQuanLyNhanVien;
    private javax.swing.JLabel txtThanhToan;
    private javax.swing.JLabel txtThanhToan1;
    // End of variables declaration//GEN-END:variables
}
