/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.ViewQL;

import View.ViewLogin;
import View.ViewNV.ViewLichSu;
import View.ViewNV.ViewThanhToan;
import View.ViewNV.ViewQuanLyBan;
import View.ViewNhanVien;
import java.awt.Color;

/**
 *
 * @author Admin
 */
public class ViewQuanLy extends javax.swing.JFrame {

    /**
     * Creates new form ViewQuanLy
     */
    private Color defaulColor, clickedColor;

    public ViewQuanLy() {
        initComponents();
        defaulColor = new Color(145, 94, 65);
        clickedColor = new Color(156, 132, 122);
        QuanLySanPham.setBackground(defaulColor);
        ThongKe.setBackground(defaulColor);
        QuanLyHoaDon.setBackground(defaulColor);
        QuanLyKhuyenMai.setBackground(defaulColor);
        QuanLyNhanVien.setBackground(defaulColor);
        QuanLyCombo.setBackground(defaulColor);
        DangXuat.setBackground(defaulColor);

        QuanLySanPham.setBackground(clickedColor);
        ThongKe.setBackground(defaulColor);
        QuanLyHoaDon.setBackground(defaulColor);
        QuanLyKhuyenMai.setBackground(defaulColor);
        QuanLyNhanVien.setBackground(defaulColor);
        QuanLyCombo.setBackground(defaulColor);
        DangXuat.setBackground(defaulColor);

        ViewQuanLySanPham m = new ViewQuanLySanPham();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(m).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        QuanLyKhuyenMai = new javax.swing.JPanel();
        txtQuanLyKhuyenMai = new javax.swing.JLabel();
        QuanLySanPham = new javax.swing.JPanel();
        txtThanhToan = new javax.swing.JLabel();
        ThongKe = new javax.swing.JPanel();
        txtLichSuOrder = new javax.swing.JLabel();
        QuanLyHoaDon = new javax.swing.JPanel();
        txtQuanLyHoaDOn = new javax.swing.JLabel();
        DangXuat = new javax.swing.JPanel();
        txtDangXuat = new javax.swing.JLabel();
        QuanLyNhanVien = new javax.swing.JPanel();
        txtQuanLyNhanVien = new javax.swing.JLabel();
        QuanLyCombo = new javax.swing.JPanel();
        txtQuanLyCombo = new javax.swing.JLabel();
        anh = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(145, 94, 65));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel2MouseMoved(evt);
            }
        });

        QuanLyKhuyenMai.setBackground(new java.awt.Color(156, 132, 122));

        txtQuanLyKhuyenMai.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtQuanLyKhuyenMai.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtQuanLyKhuyenMai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/promotion (1).png"))); // NOI18N
        txtQuanLyKhuyenMai.setText("       Quản lý khuyến mãi");
        txtQuanLyKhuyenMai.setToolTipText("");
        txtQuanLyKhuyenMai.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtQuanLyKhuyenMaiMouseMoved(evt);
            }
        });
        txtQuanLyKhuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtQuanLyKhuyenMaiMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtQuanLyKhuyenMaiMousePressed(evt);
            }
        });

        javax.swing.GroupLayout QuanLyKhuyenMaiLayout = new javax.swing.GroupLayout(QuanLyKhuyenMai);
        QuanLyKhuyenMai.setLayout(QuanLyKhuyenMaiLayout);
        QuanLyKhuyenMaiLayout.setHorizontalGroup(
            QuanLyKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 325, Short.MAX_VALUE)
            .addGroup(QuanLyKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuanLyKhuyenMaiLayout.createSequentialGroup()
                    .addGap(0, 46, Short.MAX_VALUE)
                    .addComponent(txtQuanLyKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        QuanLyKhuyenMaiLayout.setVerticalGroup(
            QuanLyKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
            .addGroup(QuanLyKhuyenMaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(txtQuanLyKhuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
        );

        QuanLySanPham.setBackground(new java.awt.Color(156, 132, 122));

        txtThanhToan.setBackground(new java.awt.Color(156, 132, 122));
        txtThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtThanhToan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/coffee (1).png"))); // NOI18N
        txtThanhToan.setText("       Quản lý sản phẩm");
        txtThanhToan.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtThanhToanMouseMoved(evt);
            }
        });
        txtThanhToan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtThanhToanMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtThanhToanMousePressed(evt);
            }
        });

        javax.swing.GroupLayout QuanLySanPhamLayout = new javax.swing.GroupLayout(QuanLySanPham);
        QuanLySanPham.setLayout(QuanLySanPhamLayout);
        QuanLySanPhamLayout.setHorizontalGroup(
            QuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuanLySanPhamLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        QuanLySanPhamLayout.setVerticalGroup(
            QuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuanLySanPhamLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        ThongKe.setBackground(new java.awt.Color(156, 132, 122));

        txtLichSuOrder.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtLichSuOrder.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtLichSuOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bar-chart (1).png"))); // NOI18N
        txtLichSuOrder.setText("       Thống kê");
        txtLichSuOrder.setToolTipText("");
        txtLichSuOrder.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtLichSuOrderMouseMoved(evt);
            }
        });
        txtLichSuOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLichSuOrderMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtLichSuOrderMousePressed(evt);
            }
        });

        javax.swing.GroupLayout ThongKeLayout = new javax.swing.GroupLayout(ThongKe);
        ThongKe.setLayout(ThongKeLayout);
        ThongKeLayout.setHorizontalGroup(
            ThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ThongKeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtLichSuOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ThongKeLayout.setVerticalGroup(
            ThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThongKeLayout.createSequentialGroup()
                .addComponent(txtLichSuOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        QuanLyHoaDon.setBackground(new java.awt.Color(156, 132, 122));

        txtQuanLyHoaDOn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtQuanLyHoaDOn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtQuanLyHoaDOn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bill (1).png"))); // NOI18N
        txtQuanLyHoaDOn.setText("       Quản lý hoá đơn");
        txtQuanLyHoaDOn.setToolTipText("");
        txtQuanLyHoaDOn.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtQuanLyHoaDOnMouseMoved(evt);
            }
        });
        txtQuanLyHoaDOn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtQuanLyHoaDOnMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtQuanLyHoaDOnMousePressed(evt);
            }
        });

        javax.swing.GroupLayout QuanLyHoaDonLayout = new javax.swing.GroupLayout(QuanLyHoaDon);
        QuanLyHoaDon.setLayout(QuanLyHoaDonLayout);
        QuanLyHoaDonLayout.setHorizontalGroup(
            QuanLyHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 325, Short.MAX_VALUE)
            .addGroup(QuanLyHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuanLyHoaDonLayout.createSequentialGroup()
                    .addGap(0, 47, Short.MAX_VALUE)
                    .addComponent(txtQuanLyHoaDOn, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        QuanLyHoaDonLayout.setVerticalGroup(
            QuanLyHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 64, Short.MAX_VALUE)
            .addGroup(QuanLyHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(txtQuanLyHoaDOn, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
        );

        DangXuat.setBackground(new java.awt.Color(156, 132, 122));

        txtDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtDangXuat.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logout (1).png"))); // NOI18N
        txtDangXuat.setText("         Đăng xuất");
        txtDangXuat.setToolTipText("");
        txtDangXuat.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtDangXuatMouseMoved(evt);
            }
        });
        txtDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDangXuatMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDangXuatMousePressed(evt);
            }
        });

        javax.swing.GroupLayout DangXuatLayout = new javax.swing.GroupLayout(DangXuat);
        DangXuat.setLayout(DangXuatLayout);
        DangXuatLayout.setHorizontalGroup(
            DangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DangXuatLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        DangXuatLayout.setVerticalGroup(
            DangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        QuanLyNhanVien.setBackground(new java.awt.Color(156, 132, 122));

        txtQuanLyNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtQuanLyNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtQuanLyNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/team (1).png"))); // NOI18N
        txtQuanLyNhanVien.setText("        Quản lý nhân viên");
        txtQuanLyNhanVien.setToolTipText("");
        txtQuanLyNhanVien.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtQuanLyNhanVienMouseMoved(evt);
            }
        });
        txtQuanLyNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtQuanLyNhanVienMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtQuanLyNhanVienMousePressed(evt);
            }
        });

        javax.swing.GroupLayout QuanLyNhanVienLayout = new javax.swing.GroupLayout(QuanLyNhanVien);
        QuanLyNhanVien.setLayout(QuanLyNhanVienLayout);
        QuanLyNhanVienLayout.setHorizontalGroup(
            QuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 325, Short.MAX_VALUE)
            .addGroup(QuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuanLyNhanVienLayout.createSequentialGroup()
                    .addGap(0, 42, Short.MAX_VALUE)
                    .addComponent(txtQuanLyNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        QuanLyNhanVienLayout.setVerticalGroup(
            QuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 79, Short.MAX_VALUE)
            .addGroup(QuanLyNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(QuanLyNhanVienLayout.createSequentialGroup()
                    .addComponent(txtQuanLyNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        QuanLyCombo.setBackground(new java.awt.Color(156, 132, 122));

        txtQuanLyCombo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtQuanLyCombo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtQuanLyCombo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/combo (1).png"))); // NOI18N
        txtQuanLyCombo.setText("         Quản lý Combo");
        txtQuanLyCombo.setToolTipText("");
        txtQuanLyCombo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                txtQuanLyComboMouseMoved(evt);
            }
        });
        txtQuanLyCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtQuanLyComboMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtQuanLyComboMousePressed(evt);
            }
        });

        javax.swing.GroupLayout QuanLyComboLayout = new javax.swing.GroupLayout(QuanLyCombo);
        QuanLyCombo.setLayout(QuanLyComboLayout);
        QuanLyComboLayout.setHorizontalGroup(
            QuanLyComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 325, Short.MAX_VALUE)
            .addGroup(QuanLyComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuanLyComboLayout.createSequentialGroup()
                    .addGap(0, 40, Short.MAX_VALUE)
                    .addComponent(txtQuanLyCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        QuanLyComboLayout.setVerticalGroup(
            QuanLyComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
            .addGroup(QuanLyComboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(QuanLyComboLayout.createSequentialGroup()
                    .addComponent(txtQuanLyCombo, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        anh.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        anh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/zyro-image (1).png"))); // NOI18N
        anh.setText("DrinkPush");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(QuanLySanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(QuanLyKhuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(QuanLyHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(QuanLyNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(QuanLyCombo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(anh, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(anh)
                .addGap(18, 18, 18)
                .addComponent(QuanLySanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(QuanLyHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(QuanLyKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(QuanLyNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(QuanLyCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 784, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 678, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jDesktopPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtQuanLyKhuyenMaiMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtQuanLyKhuyenMaiMouseMoved
        QuanLySanPham.setBackground(defaulColor);
        ThongKe.setBackground(defaulColor);
        QuanLyHoaDon.setBackground(defaulColor);
        QuanLyKhuyenMai.setBackground(clickedColor);
        QuanLyNhanVien.setBackground(defaulColor);
        QuanLyCombo.setBackground(defaulColor);
        DangXuat.setBackground(defaulColor);
    }//GEN-LAST:event_txtQuanLyKhuyenMaiMouseMoved

    private void txtQuanLyKhuyenMaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtQuanLyKhuyenMaiMouseClicked
        ViewKhuyenMai m = new ViewKhuyenMai();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(m).setVisible(true);
    }//GEN-LAST:event_txtQuanLyKhuyenMaiMouseClicked

    private void txtQuanLyKhuyenMaiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtQuanLyKhuyenMaiMousePressed
        QuanLySanPham.setBackground(defaulColor);
        ThongKe.setBackground(defaulColor);
        QuanLyHoaDon.setBackground(defaulColor);
        QuanLyKhuyenMai.setBackground(clickedColor);
        QuanLyNhanVien.setBackground(defaulColor);
        QuanLyCombo.setBackground(defaulColor);
        DangXuat.setBackground(defaulColor);
    }//GEN-LAST:event_txtQuanLyKhuyenMaiMousePressed

    private void txtThanhToanMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtThanhToanMouseMoved
        QuanLySanPham.setBackground(clickedColor);
        ThongKe.setBackground(defaulColor);
        QuanLyHoaDon.setBackground(defaulColor);
        QuanLyKhuyenMai.setBackground(defaulColor);
        QuanLyNhanVien.setBackground(defaulColor);
        QuanLyCombo.setBackground(defaulColor);
        DangXuat.setBackground(defaulColor);
    }//GEN-LAST:event_txtThanhToanMouseMoved

    private void txtThanhToanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtThanhToanMouseClicked
        ViewQuanLySanPham m = new ViewQuanLySanPham();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(m).setVisible(true);
    }//GEN-LAST:event_txtThanhToanMouseClicked

    private void txtThanhToanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtThanhToanMousePressed
        QuanLySanPham.setBackground(clickedColor);
        ThongKe.setBackground(defaulColor);
        QuanLyHoaDon.setBackground(defaulColor);
        QuanLyKhuyenMai.setBackground(defaulColor);
        QuanLyNhanVien.setBackground(defaulColor);
        QuanLyCombo.setBackground(defaulColor);
        DangXuat.setBackground(defaulColor);
    }//GEN-LAST:event_txtThanhToanMousePressed

    private void txtLichSuOrderMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLichSuOrderMouseMoved
        QuanLySanPham.setBackground(defaulColor);
        ThongKe.setBackground(clickedColor);
        QuanLyHoaDon.setBackground(defaulColor);
        QuanLyKhuyenMai.setBackground(defaulColor);
        QuanLyNhanVien.setBackground(defaulColor);
        QuanLyCombo.setBackground(defaulColor);
        DangXuat.setBackground(defaulColor);
    }//GEN-LAST:event_txtLichSuOrderMouseMoved

    private void txtLichSuOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLichSuOrderMouseClicked
        ViewThongKe m = new ViewThongKe();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(m).setVisible(true);
    }//GEN-LAST:event_txtLichSuOrderMouseClicked

    private void txtLichSuOrderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLichSuOrderMousePressed
        QuanLySanPham.setBackground(defaulColor);
        ThongKe.setBackground(clickedColor);
        QuanLyHoaDon.setBackground(defaulColor);
        QuanLyKhuyenMai.setBackground(defaulColor);
        QuanLyNhanVien.setBackground(defaulColor);
        QuanLyCombo.setBackground(defaulColor);
        DangXuat.setBackground(defaulColor);
    }//GEN-LAST:event_txtLichSuOrderMousePressed

    private void txtQuanLyHoaDOnMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtQuanLyHoaDOnMouseMoved
        QuanLySanPham.setBackground(defaulColor);
        ThongKe.setBackground(defaulColor);
        QuanLyHoaDon.setBackground(clickedColor);
        QuanLyKhuyenMai.setBackground(defaulColor);
        QuanLyNhanVien.setBackground(defaulColor);
        QuanLyCombo.setBackground(defaulColor);
        DangXuat.setBackground(defaulColor);
    }//GEN-LAST:event_txtQuanLyHoaDOnMouseMoved

    private void txtQuanLyHoaDOnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtQuanLyHoaDOnMouseClicked
        ViewQuanLyHoaDon m = new ViewQuanLyHoaDon();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(m).setVisible(true);
    }//GEN-LAST:event_txtQuanLyHoaDOnMouseClicked

    private void txtQuanLyHoaDOnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtQuanLyHoaDOnMousePressed
        QuanLySanPham.setBackground(defaulColor);
        ThongKe.setBackground(defaulColor);
        QuanLyHoaDon.setBackground(clickedColor);
        QuanLyKhuyenMai.setBackground(defaulColor);
        QuanLyNhanVien.setBackground(defaulColor);
        QuanLyCombo.setBackground(defaulColor);
        DangXuat.setBackground(defaulColor);
    }//GEN-LAST:event_txtQuanLyHoaDOnMousePressed

    private void txtDangXuatMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDangXuatMouseMoved
        QuanLySanPham.setBackground(defaulColor);
        ThongKe.setBackground(defaulColor);
        QuanLyHoaDon.setBackground(defaulColor);
        QuanLyKhuyenMai.setBackground(defaulColor);
        QuanLyNhanVien.setBackground(defaulColor);
        QuanLyCombo.setBackground(defaulColor);
        DangXuat.setBackground(clickedColor);
    }//GEN-LAST:event_txtDangXuatMouseMoved

    private void txtDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDangXuatMouseClicked
        this.dispose();
        ViewLogin m = new ViewLogin();
        m.setVisible(true);
    }//GEN-LAST:event_txtDangXuatMouseClicked

    private void txtDangXuatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDangXuatMousePressed
        QuanLySanPham.setBackground(defaulColor);
        ThongKe.setBackground(defaulColor);
        QuanLyHoaDon.setBackground(defaulColor);
        QuanLyKhuyenMai.setBackground(defaulColor);
        QuanLyNhanVien.setBackground(defaulColor);
        QuanLyCombo.setBackground(defaulColor);
        DangXuat.setBackground(clickedColor);
    }//GEN-LAST:event_txtDangXuatMousePressed

    private void txtQuanLyNhanVienMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtQuanLyNhanVienMouseMoved
        QuanLySanPham.setBackground(defaulColor);
        ThongKe.setBackground(defaulColor);
        QuanLyHoaDon.setBackground(defaulColor);
        QuanLyKhuyenMai.setBackground(defaulColor);
        QuanLyNhanVien.setBackground(clickedColor);
        QuanLyCombo.setBackground(defaulColor);
        DangXuat.setBackground(defaulColor);
    }//GEN-LAST:event_txtQuanLyNhanVienMouseMoved

    private void txtQuanLyNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtQuanLyNhanVienMouseClicked
        View.ViewQL.ViewQuanLyNhanVien m = new View.ViewQL.ViewQuanLyNhanVien();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(m).setVisible(true);
    }//GEN-LAST:event_txtQuanLyNhanVienMouseClicked

    private void txtQuanLyNhanVienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtQuanLyNhanVienMousePressed
        QuanLySanPham.setBackground(defaulColor);
        ThongKe.setBackground(defaulColor);
        QuanLyHoaDon.setBackground(defaulColor);
        QuanLyKhuyenMai.setBackground(defaulColor);
        QuanLyNhanVien.setBackground(clickedColor);
        QuanLyCombo.setBackground(defaulColor);
        DangXuat.setBackground(defaulColor);
    }//GEN-LAST:event_txtQuanLyNhanVienMousePressed

    private void txtQuanLyComboMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtQuanLyComboMouseMoved
        QuanLySanPham.setBackground(defaulColor);
        ThongKe.setBackground(defaulColor);
        QuanLyHoaDon.setBackground(defaulColor);
        QuanLyKhuyenMai.setBackground(defaulColor);
        QuanLyNhanVien.setBackground(defaulColor);
        QuanLyCombo.setBackground(clickedColor);
        DangXuat.setBackground(defaulColor);
    }//GEN-LAST:event_txtQuanLyComboMouseMoved

    private void txtQuanLyComboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtQuanLyComboMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuanLyComboMouseClicked

    private void txtQuanLyComboMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtQuanLyComboMousePressed
        QuanLySanPham.setBackground(defaulColor);
        ThongKe.setBackground(defaulColor);
        QuanLyHoaDon.setBackground(defaulColor);
        QuanLyKhuyenMai.setBackground(defaulColor);
        QuanLyNhanVien.setBackground(defaulColor);
        QuanLyCombo.setBackground(clickedColor);
        DangXuat.setBackground(defaulColor);
    }//GEN-LAST:event_txtQuanLyComboMousePressed

    private void jPanel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseMoved
        QuanLySanPham.setBackground(defaulColor);
        ThongKe.setBackground(defaulColor);
        QuanLyHoaDon.setBackground(defaulColor);
        QuanLyKhuyenMai.setBackground(defaulColor);
        QuanLyNhanVien.setBackground(defaulColor);
        QuanLyCombo.setBackground(defaulColor);
        DangXuat.setBackground(defaulColor);
    }//GEN-LAST:event_jPanel2MouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewQuanLy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DangXuat;
    private javax.swing.JPanel QuanLyCombo;
    private javax.swing.JPanel QuanLyHoaDon;
    private javax.swing.JPanel QuanLyKhuyenMai;
    private javax.swing.JPanel QuanLyNhanVien;
    private javax.swing.JPanel QuanLySanPham;
    private javax.swing.JPanel ThongKe;
    private javax.swing.JLabel anh;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txtDangXuat;
    private javax.swing.JLabel txtLichSuOrder;
    private javax.swing.JLabel txtQuanLyCombo;
    private javax.swing.JLabel txtQuanLyHoaDOn;
    private javax.swing.JLabel txtQuanLyKhuyenMai;
    private javax.swing.JLabel txtQuanLyNhanVien;
    private javax.swing.JLabel txtThanhToan;
    // End of variables declaration//GEN-END:variables
}
